"""
pre-compact-preserve.py - PreCompact hook for aios-core
Preserves critical session state before context compression.
Writes a recovery file at .tmp/compact-context.md that the
SessionStart hook detects on the next cycle.

Exit codes: 0 = success, 2 = blocking error
Target: sub-50ms execution
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def get_git_status():
    """Get uncommitted changes from git."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().splitlines()
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass
    return []


def get_git_diff_stat():
    """Get diff stats for uncommitted changes."""
    try:
        result = subprocess.run(
            ["git", "diff", "--stat"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass
    return None


def get_recent_commits(count=3):
    """Get the last N commit messages."""
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-n", str(count)],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().splitlines()
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass
    return []


def read_session_state():
    """Read any session state files from .tmp/."""
    cwd = os.getcwd()
    state = {}

    # Check for auto-sync tracking
    tracking = os.path.join(cwd, ".tmp", "modified-this-session.json")
    if os.path.isfile(tracking):
        try:
            with open(tracking, "r", encoding="utf-8") as f:
                state["modified_files"] = json.load(f)
        except (json.JSONDecodeError, OSError):
            pass

    return state


def main():
    cwd = os.getcwd()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    workspace = os.path.basename(cwd)

    lines = [
        "# Compact Context Recovery",
        "",
        "Generated by aios-core PreCompact hook at %s" % timestamp,
        "Workspace: %s" % workspace,
        "CWD: %s" % cwd,
        "",
    ]

    # Git status
    git_changes = get_git_status()
    if git_changes:
        lines.append("## Uncommitted Changes")
        lines.append("")
        for change in git_changes:
            lines.append("- %s" % change)
        lines.append("")

        diff_stat = get_git_diff_stat()
        if diff_stat:
            lines.append("```")
            lines.append(diff_stat)
            lines.append("```")
            lines.append("")

    # Recent commits
    recent = get_recent_commits(5)  # Match README: last 5 commits
    if recent:
        lines.append("## Recent Commits")
        lines.append("")
        for commit in recent:
            lines.append("- %s" % commit)
        lines.append("")

    # Session state
    session_state = read_session_state()
    if session_state.get("modified_files"):
        lines.append("## Files Modified This Session")
        lines.append("")
        for entry in session_state["modified_files"]:
            if isinstance(entry, dict):
                lines.append("- %s (%s)" % (entry.get("path", "?"), entry.get("tool", "?")))
            else:
                lines.append("- %s" % str(entry))
        lines.append("")

    # Recovery instructions
    lines.extend([
        "## Recovery Instructions",
        "",
        "After compaction, read this file to restore context.",
        "Then read MEMORY.md for full project state.",
        "Check the uncommitted changes above to understand what was in progress.",
        "",
    ])

    # Write recovery file
    tmp_dir = os.path.join(cwd, ".tmp")
    os.makedirs(tmp_dir, exist_ok=True)
    recovery_path = os.path.join(tmp_dir, "compact-context.md")

    try:
        with open(recovery_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        # stdout: brief confirmation
        print("[aios-core] Context preserved to .tmp/compact-context.md (%d lines)" % len(lines))
    except OSError as e:
        print("[aios-core] Failed to write recovery file: %s" % e, file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
